### ISSUE TITLE
Lightning icon no longer working (on/off isn't working) 

### ISSUE THREAD

**Issue by Zappline** [kantlivelong/OctoPrint-PSUControl-RPiGPIO#10]
Updated to psu controller 1.0.2, installed RPI.GPIO 1.0.1 setting it up as best as I'm able.
General: board
Switching: pin 3 (made sure its the correct one)
Sensing: 0

After hitting save the printer turns on. However the lightning bolt does not turn green or indicate the printer is on. Clicking it does nothing.

Went back in to settings and ticked "invert" and hit save. This turns the printer off, and the lightning is greyed out. However, no matter how many times I hit it. It won't turn green and the printer does not power up.

So the only way for me at this moment is to go into settings and tick or unstick the invert button to turn the printer on and off... Rather annoying.

It might be something easy I just can't figure out or there is a rather annoying issue here.

Being able to download and install an older version (that I know works) of the add-on would have been nice and would have saved my from a serious headache. But couldn't find that as an option either.

#### What did you expect to happen?
Being able to turn the printer on and off 

#### What happened instead?
Nothing, the lightning bolt icon isn't triggering anything

#### Version of OctoPrint-PSUControl
1.0.2

#### Version of OctoPrint-PSUControl-RPiGPIO
1.0.1

#### Operating System running OctoPrint
OctoPi v0.17.0

Printer: Artillery Sidewinder X1 (if that helps)
Firmware: Klipper
OctoPrint: 1.5.3

**Comment by kantlivelong** [comment]
Fill out the required info for new tickets.

**Comment by Zappline** [comment]
> Fill out the required info for new tickets.

I think this is the best I can do. I'm not very good at these things.

**Comment by kantlivelong** [comment]
Sorry but I really can't and won't do anything without logs.

**Comment by Zappline** [comment]
> Sorry but I really can't and won't do anything without logs.

Probably doing something wrong. But I can't generate any logs. But it's OK. Turns out over at the main page. A bunch of people have have the same issue. Guess I'll just keep my eyes open over there. Until then. I'll try to figure out how to install a pre 1.0.0 version

**Comment by kantlivelong** [comment]
Alright
