### ISSUE TITLE
Cant power on PSU with no option after update.

### ISSUE THREAD

**Issue by BlutVampir** [kantlivelong/OctoPrint-PSUControl-RPiGPIO#13]
version 0.1.11:
[this setting is working.](https://ibb.co/Z6CjgQC)

Tried to update to 1.0.4 version, but coudn't get it running.

At the highlighted pin is my Power Relay attached:
[image 1 of my pin](https://ibb.co/1mzNwL0)
GPIO 2 or Board 3.

I rechecked it, its the 2nd pin, but in 0.1.11 it was working with "GPIO 3".

 [BCM 2 not working at all (as I had GPIO 3 used before, I did test also 3 here, same effect, not working)](https://ibb.co/HYR4Gjj])
 [board 3 not working](https://ibb.co/FJphzJq)

Config wiped completly and tried without plugin:
[GPIO 2 not working (as I had GPIO 3 used before, I did test also 3 here, same effect, not working)](https://ibb.co/vX52Z9g) 

I own a Raspberry Pi 3 Model B Rev 1.2.
OctoPi Version 0.15.1 (latest)
/etc/debian_version = 9.13
All module are upgraded (apt-get update && apt-get upgrade)

Printer is not important, as the PIN doesnt get power on it when switching PSU newer than 1.x, only old 0.1.11 is powering on the pin.

**Comment by kantlivelong** [comment]
Normally I wouldn't even give a reply to this but try again and actually read and do what the form says.
