### ISSUE TITLE
Can't Close Wizard Box: Interface blocked

### ISSUE THREAD

**Issue by moarkaboom** [kantlivelong/OctoPrint-PSUControl-RPiGPIO#2]
Since updating to 1.0.0 I cant close the wizard by clicking on finish, the windows stays open blocking the whole UI.
<img width="740" alt="psu" src="https://user-images.githubusercontent.com/78112271/114992828-75e51900-9e9b-11eb-8d82-360c3732d416.png">

Edit: this actually applies to the PSUControl, not the GPIO-Plugin, but the window of the wizard links to this repo.

**Comment by valiobg** [comment]
Same issue with my Octoprint...
Please fix it ASAP.
![Screenshot 2021-04-16 13 29 15](https://user-images.githubusercontent.com/31922968/115012020-fade2b80-9eb7-11eb-978b-4144145de469.png)

**Comment by kantlivelong** [comment]
Wrong repo.

See https://github.com/kantlivelong/OctoPrint-PSUControl/issues/181
