### ISSUE TITLE
updated PSUControl to 1.0.0, warning modal cannot be closed.

### ISSUE THREAD

**Issue by d3relict** [kantlivelong/OctoPrint-PSUControl-RPiGPIO#5]
getting the following modal:
Starting with PSU Control version 1.0.0 RPi.GPIO has been dropped in favor of Python-Periphery. For the majority of users there should be no difference but please be sure to fully test your config before proceeding!

If you would like to continue using RPi.GPIO there is good news! PSU Control now supports plugins and RPi.GPIO is one of them. You can install PSU Control - RPi.GPIO from the plugin manager.

when trying to close, the following error is presented on the console:
packed_core.js?22357642:431 Uncaught TypeError: Cannot read property 'done' of undefined
    at WizardViewModel.self.finishWizard (packed_core.js?22357642:431)
    at Object.onFinish (packed_core.js?22357642:430)
    at HTMLButtonElement.finish (packed_libs.js?ab739628:1209)
    at HTMLButtonElement.dispatch (packed_libs.js?ab739628:1)
    at HTMLButtonElement.v.handle (packed_libs.js?ab739628:1)

this is happening on every reload, i can only proceed if i remove all modal elements from the dom.

**Comment by kantlivelong** [comment]
Could you provide full logs in https://github.com/kantlivelong/OctoPrint-PSUControl/issues/181

This repo is for psucontrol_rpigpio
