### ISSUE TITLE
HELP... GPIO functionality doesn't work anymore

### ISSUE THREAD

**Issue by dumbozo** [kantlivelong/OctoPrint-PSUControl-RPiGPIO#8]
Dear developer,
I use PSU control to switch my 3D printer on and of through a realy.
Especially the polling feature and the autoshutdown after x min of idle time are crucial for me.
After the last update I do not get it working as before.
I installed the seperate plugin RPi GPIO but it is not polling and the PSU icon doesn't togle the PSU anymore.
Please get it back... why fixing it while it isn't broken... now it is :-(
I hope you can help me out.
grt,
Dumb

**Comment by kantlivelong** [comment]
Try w/o PSUControl-RPi.GPIO first and if there's an issue open a ticket at https://github.com/kantlivelong/OctoPrint-PSUControl with all required info. If there is still an issue then open a new ticket here with the same issue format.
